Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 0
Watching for file changes with StatReloader
"GET /about HTTP/1.1" 301 0
"GET /about/ HTTP/1.1" 200 5
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 0
"GET / HTTP/1.1" 200 0
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\HW_project\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\HW_project\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 0
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 9
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 9
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 6, in index
    return render(request, '/templates/home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /templates/home.html
"GET / HTTP/1.1" 500 81338
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 6, in index
    return render(request, '/templates/home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /templates/home.html
"GET / HTTP/1.1" 500 81338
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 6, in index
    return render(request, 'home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /templates/home.html
"GET / HTTP/1.1" 500 81316
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 6, in index
    return render(request, 'home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
"GET / HTTP/1.1" 500 81952
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 144
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2442
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients HTTP/1.1" 301 0
Internal Server Error: /clients/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 17, in get_clients
    return render(request, 'clients.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: clients.html
"GET /clients/ HTTP/1.1" 500 89716
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 2475
"GET /clients/ HTTP/1.1" 200 2475
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 2471
"GET /clients/ HTTP/1.1" 200 2471
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 2471
"GET /clients/ HTTP/1.1" 200 2471
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 2471
"GET /clients/ HTTP/1.1" 200 2471
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 626
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 626
"GET /clients/ HTTP/1.1" 200 626
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 555
"GET /clients/ HTTP/1.1" 200 555
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 555
"GET /clients/ HTTP/1.1" 200 555
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /client?id=22 HTTP/1.1" 301 0
Internal Server Error: /client/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_client() missing 1 required positional argument: 'id'
"GET /client/?id=22 HTTP/1.1" 500 64885
Internal Server Error: /client/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_client() missing 1 required positional argument: 'id'
"GET /client/?id=22 HTTP/1.1" 500 65022
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /client/?id=22 HTTP/1.1" 200 111
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2949
"GET /order HTTP/1.1" 301 0
"GET /order/ HTTP/1.1" 200 48
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 92
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    print(**orders)
TypeError: print() argument after ** must be a mapping, not QuerySet
"GET /order/ HTTP/1.1" 500 67917
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /get_clients
"GET /get_clients HTTP/1.1" 404 2949
"GET /clients HTTP/1.1" 301 0
"GET /clients/ HTTP/1.1" 200 555
Not Found: /orders
"GET /orders HTTP/1.1" 404 2934
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /orde&id=22
"GET /orde&id=22 HTTP/1.1" 404 2960
Not Found: /orde&id=22
"GET /orde&id=22 HTTP/1.1" 404 2960
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /orde&id=22
"GET /orde&id=22 HTTP/1.1" 404 2960
Not Found: /order&id=22
"GET /order&id=22 HTTP/1.1" 404 2963
"GET /order?id=22 HTTP/1.1" 301 0
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 28, in get_order_info
    order = Order.objects.get(id=int(client_id))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hwapp.models.Order.DoesNotExist: Order matching query does not exist.
"GET /order/?id=22 HTTP/1.1" 500 77071
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 28, in get_order_info
    order = Order.objects.get(client_id=int(client_id))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hwapp.models.Order.DoesNotExist: Order matching query does not exist.
"GET /order/?id=22 HTTP/1.1" 500 77222
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/?id=22 HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/?id=22 HTTP/1.1" 200 16
"GET /order/?id=22 HTTP/1.1" 200 16
"GET /order/?id=23 HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/?id=23 HTTP/1.1" 200 16
"GET /order/?id=23 HTTP/1.1" 200 16
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    field_value = getattr(orders, 'total_cost')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'total_cost'
"GET /order/ HTTP/1.1" 500 68131
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    for i in orders:
                  ^^^
AttributeError: 'QuerySet' object has no attribute 'total_cost'
"GET /order/ HTTP/1.1" 500 68304
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1492, in build_filter
    arg, value = filter_expr
    ^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
"GET /order/ HTTP/1.1" 500 101280
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    return HttpResponse(orders.total_cost)
                        ^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'total_cost'
"GET /order/ HTTP/1.1" 500 67803
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    return HttpResponse(orders.total_cost)
                        ^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'total_cost'
"GET /order/ HTTP/1.1" 500 67803
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /clients/ HTTP/1.1" 200 555
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 66
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 24
"GET /order/ HTTP/1.1" 200 24
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 27
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
"GET /about HTTP/1.1" 301 0
"GET /about/ HTTP/1.1" 200 162
"GET /about/ HTTP/1.1" 200 162
"GET /about/ HTTP/1.1" 200 165
Watching for file changes with StatReloader
"GET /about/ HTTP/1.1" 200 165
"GET /order HTTP/1.1" 301 0
"GET /order/ HTTP/1.1" 200 16
"GET /orders/2 HTTP/1.1" 301 0
"GET /orders/2/ HTTP/1.1" 200 16
"GET /orders/2/ HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 52, in get_orders
    return HttpResponse(orders.total_cost)
                        ^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'total_cost'
"GET /orders/2/ HTTP/1.1" 500 67834
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
"GET /order/ HTTP/1.1" 200 18
"GET /orders/4 HTTP/1.1" 301 0
"GET /orders/4/ HTTP/1.1" 200 0
"GET /orders/4/ HTTP/1.1" 200 0
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/4/ HTTP/1.1" 200 0
"GET /orders/2/ HTTP/1.1" 200 16
"GET /orders/2/ HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 52, in get_orders
    print(orders.id)
          ^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'id'
"GET /orders/2/ HTTP/1.1" 500 68109
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 52, in get_orders
    print(orders.id)
          ^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'id'
"GET /orders/2/ HTTP/1.1" 500 68106
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 16
"GET /orders/2/ HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
- Broken pipe from ('127.0.0.1', 55463)
"GET /orders/2/ HTTP/1.1" 200 36
"GET /orders/1/ HTTP/1.1" 200 0
"GET /orders/1/ HTTP/1.1" 200 0
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 52, in get_orders
    return HttpResponse(products.product_name)
                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'product_name'
"GET /orders/2/ HTTP/1.1" 500 67777
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 52, in get_orders
    return HttpResponse(products.product_id)
                        ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'product_name'
"GET /orders/2/ HTTP/1.1" 500 67910
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 52, in get_orders
    return HttpResponse(products.product_id)
                        ^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'product_id'
"GET /orders/2/ HTTP/1.1" 500 67898
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 36
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 54
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 54
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 52, in get_orders
    return render(request, 'orders.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: orders.html
"GET /orders/2/ HTTP/1.1" 500 83619
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 52, in get_orders
    return render(request, 'orders.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: orders.html
"GET /orders/2/ HTTP/1.1" 500 83619
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 357
"GET /orders/2/ HTTP/1.1" 200 357
"GET /orders/2/ HTTP/1.1" 200 321
"GET /orders/1/ HTTP/1.1" 200 235
Watching for file changes with StatReloader
Internal Server Error: /orders/1/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 51, in get_orders
    client = Client.objects.get(client_id=int(client_id))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'client_id' into field. Choices are: address, email, id, name, order, phone, registered_date
"GET /orders/1/ HTTP/1.1" 500 118662
Internal Server Error: /orders/1/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 51, in get_orders
    client = Client.objects.get(id=int(client_id))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'client_id' into field. Choices are: address, email, id, name, order, phone, registered_date
"GET /orders/1/ HTTP/1.1" 500 118648
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/1/ HTTP/1.1" 200 244
"GET /orders/2/ HTTP/1.1" 200 326
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 412
"GET /orders/2/ HTTP/1.1" 200 412
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 412
"GET /orders/2/ HTTP/1.1" 200 412
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 412
"GET /orders/2/ HTTP/1.1" 200 412
"GET /orders/2/ HTTP/1.1" 200 412
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 56, in get_orders
    products = Product.objects.filter(order__client_id = client_id,date_ordered__gte=datetime.now()-timedelta(days=7))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_ordered' into field. Choices are: added_date, description, id, order, price, product_name, quantity
"GET /orders/2/ HTTP/1.1" 500 114055
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 16
"GET /orders/2/ HTTP/1.1" 200 16
"GET /orders/2/ HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 16
"GET /orders/2/ HTTP/1.1" 200 16
"GET /orders/2/ HTTP/1.1" 200 16
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 32
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 55, in get_orders
    products = Product.objects.filter(order__client_id = client_id,date_ordered__gte=datetime.now()-timedelta(days=7))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_ordered' into field. Choices are: added_date, description, id, order, price, product_name, quantity
"GET /orders/2/ HTTP/1.1" 500 114656
Internal Server Error: /orders/2/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 55, in get_orders
    products = Product.objects.filter(order__client_id = client_id,order__date_ordered__gte=datetime.now()-timedelta(days=7))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_ordered' into field. Choices are: added_date, description, id, order, price, product_name, quantity
"GET /orders/2/ HTTP/1.1" 500 114661
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 283
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/ HTTP/1.1" 200 412
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3158
"GET /order/ HTTP/1.1" 200 18
Not Found: /orders/
"GET /orders/ HTTP/1.1" 404 3146
Not Found: /orders/2/
"GET /orders/2/ HTTP/1.1" 404 3152
"GET /orders/2/week HTTP/1.1" 200 197
"GET /orders/2/week HTTP/1.1" 200 197
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /orders/2/week HTTP/1.1" 200 197
"GET /orders/2/month HTTP/1.1" 200 197
"GET /orders/2/year HTTP/1.1" 200 283
"GET /orders/2/year HTTP/1.1" 200 412
"GET /orders/2/month HTTP/1.1" 200 326
Not Found: /orders/2/
"GET /orders/2/ HTTP/1.1" 404 3152
"GET /orders/2/week HTTP/1.1" 200 326
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
"GET /add_product HTTP/1.1" 301 0
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 80, in add_product
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /add_product/ HTTP/1.1" 500 74353
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 82, in add_product
    return render(request, 'hwapp/forms_render.html', {'form': form})
                                                               ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
"GET /add_product/ HTTP/1.1" 500 68400
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 82, in add_product
    # return render(request, 'hwapp/forms_render.html', {'form': form})
                                                               ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
"GET /add_product/ HTTP/1.1" 500 68404
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view hwapp.views.add_product didn't return an HttpResponse object. It returned None instead.
"GET /add_product/ HTTP/1.1" 500 69978
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view hwapp.views.add_product didn't return an HttpResponse object. It returned None instead.
"GET /add_product/ HTTP/1.1" 500 69978
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /add_product/ HTTP/1.1" 200 5
"GET /add_product/ HTTP/1.1" 200 5
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 81, in add_product
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /add_product/ HTTP/1.1" 500 74417
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 81, in add_product
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /add_product/ HTTP/1.1" 500 74417
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 81, in add_product
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /add_product/ HTTP/1.1" 500 74417
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 81, in add_product
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /add_product/ HTTP/1.1" 500 74417
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 81, in add_product
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /add_product/ HTTP/1.1" 500 74417
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 81, in add_product
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /add_product/ HTTP/1.1" 500 74417
Internal Server Error: /add_product/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 81, in add_product
    form = ProductForm()
           ^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 360, in __init__
    raise ValueError("ModelForm has no model class specified.")
ValueError: ModelForm has no model class specified.
"GET /add_product/ HTTP/1.1" 500 74417
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /add_product/ HTTP/1.1" 200 1190
"POST /add_product/ HTTP/1.1" 200 23
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\HW_project\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /upload_img HTTP/1.1" 301 0
"GET /upload_img/ HTTP/1.1" 200 585
Internal Server Error: /upload_img/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 90, in upload_image
    if form.is_valid():
       ^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\forms.py", line 327, in full_clean
    self._clean_fields()
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\forms.py", line 337, in _clean_fields
    value = field.clean(value, bf.initial)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\fields.py", line 689, in clean
    return super().clean(data)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\fields.py", line 204, in clean
    value = self.to_python(value)
            ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\fields.py", line 716, in to_python
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
"POST /upload_img/ HTTP/1.1" 500 98505
Watching for file changes with StatReloader
"POST /upload_img/ HTTP/1.1" 200 585
"POST /upload_img/ HTTP/1.1" 200 585
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3516
Watching for file changes with StatReloader
"GET /test HTTP/1.1" 301 0
"GET /test/ HTTP/1.1" 200 819
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /test/ HTTP/1.1" 200 819
"GET /test/ HTTP/1.1" 200 819
"GET /test/ HTTP/1.1" 200 819
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
"GET /test/ HTTP/1.1" 200 819
"GET /test/ HTTP/1.1" 200 819
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/ HTTP/1.1" 200 819
"GET /test/ HTTP/1.1" 200 819
"GET /test/ HTTP/1.1" 200 819
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/ HTTP/1.1" 200 819
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/ HTTP/1.1" 200 819
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/ HTTP/1.1" 200 819
"GET /test/ HTTP/1.1" 200 819
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/ HTTP/1.1" 200 789
"GET /test/ HTTP/1.1" 200 789
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/ HTTP/1.1" 200 1612
"GET /test/ HTTP/1.1" 200 1612
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/ HTTP/1.1" 200 789
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/ HTTP/1.1" 200 814
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 101, in test
    print(form.cleaned_data)
          ^^^^^^^^^^^^^^^^^
AttributeError: 'ChoiceForm' object has no attribute 'cleaned_data'. Did you mean: 'changed_data'?
"POST /test/ HTTP/1.1" 500 69840
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 944
"POST /test/ HTTP/1.1" 200 944
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 101, in test
    print(form.changed_data['product_name'])
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
"POST /test/ HTTP/1.1" 500 69803
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 944
"POST /test/ HTTP/1.1" 200 944
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 101, in test
    print(form.changed_data[1])
          ~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
"POST /test/ HTTP/1.1" 500 69635
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 944
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 105, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
                                                               ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
"POST /test/ HTTP/1.1" 500 69114
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 106, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
                                                               ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
"POST /test/ HTTP/1.1" 500 69081
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 967
"POST /test/ HTTP/1.1" 200 967
"POST /test/ HTTP/1.1" 200 967
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 944
"POST /test/ HTTP/1.1" 200 944
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'product_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 101, in test
    pr = Product.objects.filter(product_name=request.POST['product_name'])
                                             ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'product_name'
"POST /test/ HTTP/1.1" 500 78661
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 944
"POST /test/ HTTP/1.1" 200 944
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 102, in test
    print(form.cleaned_data)
          ^^^^^^^^^^^^^^^^^
AttributeError: 'ChoiceForm' object has no attribute 'cleaned_data'. Did you mean: 'changed_data'?
"POST /test/ HTTP/1.1" 500 69831
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 944
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 460
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 1554
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 460
"POST /test/ HTTP/1.1" 200 460
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 839
"POST /test/ HTTP/1.1" 200 896
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 896
"POST /test/ HTTP/1.1" 200 896
"POST /test/ HTTP/1.1" 200 896
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 101, in test
    print(form.cleaned_data)
          ^^^^^^^^^^^^^^^^^
AttributeError: 'ChoiceForm' object has no attribute 'cleaned_data'. Did you mean: 'changed_data'?
"POST /test/ HTTP/1.1" 500 70073
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 896
"POST /test/ HTTP/1.1" 200 896
"POST /test/ HTTP/1.1" 200 896
"POST /test/ HTTP/1.1" 200 896
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 107, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
                                                               ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
"POST /test/ HTTP/1.1" 500 69005
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 814
"POST /test/ HTTP/1.1" 200 814
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 814
"POST /test/ HTTP/1.1" 200 814
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 814
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 814
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 814
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"POST /test/ HTTP/1.1" 200 1637
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 108, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
                                                               ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
"POST /test/ HTTP/1.1" 500 69035
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 108, in test
    form = ChoiceForm(
           ^^^^^^^^^^^
TypeError: BaseForm.__init__() got an unexpected keyword argument 'product_name'
"GET /test/2 HTTP/1.1" 500 68770
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 111, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 87, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 55, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 95, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 270, in build_widget_attrs
    widget.use_required_attribute(self.initial)
                                  ^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 264, in initial
    return self.form.get_initial_for_field(self.field, self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\forms.py", line 414, in get_initial_for_field
    value = self.initial.get(field_name, field.initial)
            ^^^^^^^^^^^^^^^^
AttributeError: 'decimal.Decimal' object has no attribute 'get'
"GET /test/2 HTTP/1.1" 500 239002
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 111, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 87, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 55, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 95, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 270, in build_widget_attrs
    widget.use_required_attribute(self.initial)
                                  ^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 264, in initial
    return self.form.get_initial_for_field(self.field, self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\forms.py", line 414, in get_initial_for_field
    value = self.initial.get(field_name, field.initial)
            ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'get'
"GET /test/2 HTTP/1.1" 500 238948
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 111, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 87, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 55, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 95, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 270, in build_widget_attrs
    widget.use_required_attribute(self.initial)
                                  ^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 264, in initial
    return self.form.get_initial_for_field(self.field, self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\forms.py", line 414, in get_initial_for_field
    value = self.initial.get(field_name, field.initial)
            ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'get'
"GET /test/2 HTTP/1.1" 500 238948
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 111, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 87, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 55, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 95, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 270, in build_widget_attrs
    widget.use_required_attribute(self.initial)
                                  ^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 264, in initial
    return self.form.get_initial_for_field(self.field, self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\forms.py", line 414, in get_initial_for_field
    value = self.initial.get(field_name, field.initial)
            ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'get'
"GET /test/2 HTTP/1.1" 500 238945
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 107, in test
    product = Product.objects.get(id=product_id).first()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'first'
"GET /test/2 HTTP/1.1" 500 68926
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 107, in test
    product = Product.objects.get(id=product_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'first'
"GET /test/2 HTTP/1.1" 500 68910
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 111, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 909, in _resolve_lookup
    current = current()
              ^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 87, in as_p
    return self.render(self.template_name_p)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 55, in render
    return mark_safe(renderer.render(template, context))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\renderers.py", line 29, in render
    return template.render(context, request=request).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1065, in render
    return render_value_in_context(output, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\base.py", line 1042, in render_value_in_context
    value = str(value)
            ^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\utils.py", line 79, in __str__
    return self.as_widget()
           ^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 95, in as_widget
    attrs = self.build_widget_attrs(attrs, widget)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 270, in build_widget_attrs
    widget.use_required_attribute(self.initial)
                                  ^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\boundfield.py", line 264, in initial
    return self.form.get_initial_for_field(self.field, self.name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\forms.py", line 414, in get_initial_for_field
    value = self.initial.get(field_name, field.initial)
            ^^^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'get'
"GET /test/2 HTTP/1.1" 500 238937
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 108, in test
    form = ChoiceForm(
           ^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 370, in __init__
    object_data.update(initial)
TypeError: 'Product' object is not iterable
"GET /test/2 HTTP/1.1" 500 75096
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 108, in test
    print(product)
           ^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 370, in __init__
    object_data.update(initial)
TypeError: 'Product' object is not iterable
"GET /test/2 HTTP/1.1" 500 75236
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 112, in test
    return render(request, 'hwapp/upload_image.html', {'form': form})
                                                               ^^^^
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
"GET /test/2 HTTP/1.1" 500 68626
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 112, in test
    form = ChoiceForm()
                        
UnboundLocalError: cannot access local variable 'form' where it is not associated with a value
"GET /test/2 HTTP/1.1" 500 68830
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/2 HTTP/1.1" 200 1254
"GET /test/2 HTTP/1.1" 200 1254
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/2 HTTP/1.1" 200 1254
"GET /test/2 HTTP/1.1" 200 1254
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 109, in test
    form = ChoiceForm(
           ^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 370, in __init__
    object_data.update(initial)
TypeError: 'Product' object is not iterable
"GET /test/2 HTTP/1.1" 500 75173
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 109, in test
    form = ChoiceForm(
           ^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 370, in __init__
    object_data.update(initial)
TypeError: 'Product' object is not iterable
"GET /test/2 HTTP/1.1" 500 75172
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /test/2
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 109, in test
    form = ChoiceForm(
           ^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\forms\models.py", line 370, in __init__
    object_data.update(initial)
TypeError: 'Product' object is not iterable
"GET /test/2 HTTP/1.1" 500 75172
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/2 HTTP/1.1" 200 1296
"GET /test/2 HTTP/1.1" 200 1296
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/2 HTTP/1.1" 200 1645
"GET /test/2 HTTP/1.1" 200 1645
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\forms.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/2 HTTP/1.1" 200 1296
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/2 HTTP/1.1" 200 1296
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /test/2 HTTP/1.1" 200 1296
"GET /test/1 HTTP/1.1" 200 1303
"POST /test/1 HTTP/1.1" 200 31
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /upload_img/1 HTTP/1.1" 200 610
Internal Server Error: /upload_img/1
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\datastructures.py", line 84, in __getitem__
    list_ = super().__getitem__(key)
            ^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 100, in upload_image
    product.link_photo = request.FILES['']
                         ~~~~~~~~~~~~~^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\datastructures.py", line 86, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: ''
"POST /upload_img/1 HTTP/1.1" 500 79122
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /upload_img/1 HTTP/1.1" 200 610
"POST /upload_img/1 HTTP/1.1" 200 610
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /upload_img/1 HTTP/1.1" 200 610
"POST /upload_img/1 HTTP/1.1" 200 610
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /upload_img/1 HTTP/1.1" 200 610
"POST /upload_img/1 HTTP/1.1" 200 610
"POST /upload_img/1 HTTP/1.1" 200 610
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
"GET /update_product/2 HTTP/1.1" 200 1313
"GET /update_product/2 HTTP/1.1" 200 1313
"GET /update_product/2 HTTP/1.1" 200 1204
"GET /update_product/2 HTTP/1.1" 200 1313
"GET /update_product/2 HTTP/1.1" 200 1204
