Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 0
Watching for file changes with StatReloader
"GET /about HTTP/1.1" 301 0
"GET /about/ HTTP/1.1" 200 5
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 0
"GET / HTTP/1.1" 200 0
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\HW_project\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\HW_project\settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 0
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 9
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 9
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 6, in index
    return render(request, '/templates/home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /templates/home.html
"GET / HTTP/1.1" 500 81338
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 6, in index
    return render(request, '/templates/home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /templates/home.html
"GET / HTTP/1.1" 500 81338
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 6, in index
    return render(request, 'home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /templates/home.html
"GET / HTTP/1.1" 500 81316
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 6, in index
    return render(request, 'home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
"GET / HTTP/1.1" 500 81952
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 144
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2442
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients HTTP/1.1" 301 0
Internal Server Error: /clients/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 17, in get_clients
    return render(request, 'clients.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: clients.html
"GET /clients/ HTTP/1.1" 500 89716
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 2475
"GET /clients/ HTTP/1.1" 200 2475
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 2471
"GET /clients/ HTTP/1.1" 200 2471
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 2471
"GET /clients/ HTTP/1.1" 200 2471
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 2471
"GET /clients/ HTTP/1.1" 200 2471
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 626
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 626
"GET /clients/ HTTP/1.1" 200 626
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 555
"GET /clients/ HTTP/1.1" 200 555
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 555
"GET /clients/ HTTP/1.1" 200 555
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /client?id=22 HTTP/1.1" 301 0
Internal Server Error: /client/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_client() missing 1 required positional argument: 'id'
"GET /client/?id=22 HTTP/1.1" 500 64885
Internal Server Error: /client/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_client() missing 1 required positional argument: 'id'
"GET /client/?id=22 HTTP/1.1" 500 65022
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /client/?id=22 HTTP/1.1" 200 111
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 148
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2949
"GET /order HTTP/1.1" 301 0
"GET /order/ HTTP/1.1" 200 48
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 92
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    print(**orders)
TypeError: print() argument after ** must be a mapping, not QuerySet
"GET /order/ HTTP/1.1" 500 67917
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /get_clients
"GET /get_clients HTTP/1.1" 404 2949
"GET /clients HTTP/1.1" 301 0
"GET /clients/ HTTP/1.1" 200 555
Not Found: /orders
"GET /orders HTTP/1.1" 404 2934
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /orde&id=22
"GET /orde&id=22 HTTP/1.1" 404 2960
Not Found: /orde&id=22
"GET /orde&id=22 HTTP/1.1" 404 2960
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /orde&id=22
"GET /orde&id=22 HTTP/1.1" 404 2960
Not Found: /order&id=22
"GET /order&id=22 HTTP/1.1" 404 2963
"GET /order?id=22 HTTP/1.1" 301 0
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 28, in get_order_info
    order = Order.objects.get(id=int(client_id))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hwapp.models.Order.DoesNotExist: Order matching query does not exist.
"GET /order/?id=22 HTTP/1.1" 500 77071
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 28, in get_order_info
    order = Order.objects.get(client_id=int(client_id))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
hwapp.models.Order.DoesNotExist: Order matching query does not exist.
"GET /order/?id=22 HTTP/1.1" 500 77222
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/?id=22 HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/?id=22 HTTP/1.1" 200 16
"GET /order/?id=22 HTTP/1.1" 200 16
"GET /order/?id=23 HTTP/1.1" 200 16
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/?id=23 HTTP/1.1" 200 16
"GET /order/?id=23 HTTP/1.1" 200 16
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    field_value = getattr(orders, 'total_cost')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'total_cost'
"GET /order/ HTTP/1.1" 500 68131
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    for i in orders:
                  ^^^
AttributeError: 'QuerySet' object has no attribute 'total_cost'
"GET /order/ HTTP/1.1" 500 68304
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\middleware\clickjacking.py", line 27, in process_response
    if response.get("X-Frame-Options") is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1492, in build_filter
    arg, value = filter_expr
    ^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
"GET /order/ HTTP/1.1" 500 101280
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    return HttpResponse(orders.total_cost)
                        ^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'total_cost'
"GET /order/ HTTP/1.1" 500 67803
Internal Server Error: /order/
Traceback (most recent call last):
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py", line 31, in get_order_info
    return HttpResponse(orders.total_cost)
                        ^^^^^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'total_cost'
"GET /order/ HTTP/1.1" 500 67803
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /clients/ HTTP/1.1" 200 555
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 48
"GET /order/ HTTP/1.1" 200 48
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 66
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 24
"GET /order/ HTTP/1.1" 200 24
D:\GeekBrains\Framework_Django\Frame_Django\HW_project\HW_project\hwapp\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /order/ HTTP/1.1" 200 27
